<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Gnx.DeterministicBundle.wixext</AssemblyName>
    <RootNamespace>Gnx.DeterministicBundle</RootNamespace>
    <DebugType>embedded</DebugType>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WixToolset.Extensibility" Version="5.0.2" PrivateAssets="all" />
  </ItemGroup>
</Project>
