[package]
name = "gnx"
version = "0.3.2-rc.2"
edition = "2021"
default-run = "gnx"
[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
sha2 = "0.10"
fs2 = "0.4.3"
url = "2.5.8"
zeroize = "1.9.0"
rpassword = "7.5.4"
ed25519-dalek = "3.0.0"
hex = "0.4.3"
[target.'cfg(windows)'.dependencies]
windows-service = "0.8"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Storage_FileSystem", "Win32_System_Pipes", "Win32_System_IO", "Win32_System_Memory", "Win32_System_Threading", "Win32_System_JobObjects", "Win32_NetworkManagement_NetManagement", "Win32_Security_Authentication_Identity", "Win32_Security_Cryptography", "Win32_System_Services"] }

[target."cfg(unix)".dependencies]
libc = "0.2.189"
